---
title: "Tidy Tuesday - Week 22 - NFL 2000-2017 Player Data"
author: "Hayden MacDonald"
date: "[Current Year]"
output: github_document
---

```{r setup, echo=FALSE}
library(formatR)
library(knitr)
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=50),tidy=TRUE)

library(readxl)
library(dplyr)
library(tidyr)
library(ggplot2)
```

----

## Import Data
```{r}
fb <- read.csv("nfl_2010-2017.csv", header = TRUE)
```

----

## Wrangle

```{r}
fb2 <- fb %>%
    select(game_year, rush_fumbles, rec_fumbles, pass_fumbles) %>%
    group_by(game_year) %>%
    mutate_if(is.numeric, funs(ifelse(is.na(.), 0, .))) %>%
    summarize(pct_rush_fum = sum(rush_fumbles, na.rm = TRUE) / n() * 100, 
              pct_rec_fum = sum(rec_fumbles, na.rm = TRUE) / n() * 100, 
              pct_pass_fum = sum(pass_fumbles, na.rm = TRUE) / n() * 100)

# wide data
fb2

# convert data to long format
fb2l <- fb2 %>%
  gather(fum_type, percent_fum, -game_year)
```

----

## Visualize

```{r}
fb2l %>%
    ggplot(aes(x = game_year)) +
    geom_line(aes(y = percent_fum, group = fum_type, color = fum_type)) +
    theme_minimal() +
    scale_color_manual(name = "Fumble Type", labels = c("Pass", "Receive", "Rush"), values = c("#003399", "#aaaabb", "#cc0033")) +
    labs(x = "Year", y = "Percent Fumbled", title = "Percentage of fumbles per year by fumble type", subtitle = "Fumbles by passing, receiving or rushing") +
    theme(legend.position = c(0.5,0.8), legend.direction = "horizontal")
```













----

## Session Info

```{r}
sessionInfo()
```














