---
title: "week22"
author: "Hayden MacDonald"
date: "25/05/2020"
output: html_document
---

## Packages

```{r}
library(tidyverse)
library(ggplot2)
library(ggridges)
library(Cairo)
library(glue)
library(patchwork)
```



## Import

```{r}
boston <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-26/boston_cocktails.csv')
```


## Alcohol

```{r}
alcohol <- c("gin", "vodka", "rum", "rye", "whiskey", "whisky", "brandy", "cognac", "tequila", "schnapps", "jack daniel")

alc_sweet <- c("cointreau", "triple sec", "apple jack", "amaretto", "anisette")

alc_sour <- c("port", "wine")

alc_bitter <- c("beer", "bitter", "bitters", "campari", "cynar", "fernet-branca")

all_alc <- c(alc_sweet, alc_sour, alc_bitter, "dry vermouth", "sweet vermouth")
```


## Fruit

```{r}
fruit_sour <- c("lemon", "lime", "orange", "blackberry", "blackcurrant", "blood orange", "currant", "redcurrant", "elderberry", "grape", "pomegranate", "raspberry", "tangerine", "mandarine", "sour mix")

fruit_bitter <- c("cranberry", "grapefruit", "olive")

fruit_sweet <- fruit[!(fruit %in% fruit_sour | fruit %in% fruit_bitter)]
```


## Sweets

```{r}
sweets <- c("syrup", "grenadine", "sugar", "mint", "cream")
```



Question: What are the parts distributions of ?

```{r}
boston <- boston %>%
            filter(!(name == "Glogg" & name == "Eggnog Supreme" & name == "Bloody Scotsman" & category != "Non-alcoholic Drinks" & category != "Shooters")) %>%
            mutate(ingredient = tolower(ingredient)) %>%
            group_by(ingredient) %>%
            mutate(spirit = if_else(TRUE %in% str_detect(ingredient, alcohol), 1, 0),
                   ingred_alc = if_else(TRUE %in% str_detect(ingredient, all_alc), 1, 0),
                   ingred_sour = if_else(TRUE %in% str_detect(ingredient, fruit_sour), 1, 0),
                   ingred_sweet = if_else(TRUE %in% str_detect(ingredient, fruit_sweet) | TRUE %in% str_detect(ingredient, sweets), 1, 0),
                   ingred_bitter = if_else(TRUE %in% str_detect(ingredient, fruit_bitter) | TRUE %in% str_detect(ingredient, alc_bitter), 1, 0)) %>%
            ungroup() %>%
            mutate(ingred_alc = if_else(str_detect(ingredient, "bitter"), 0, ingred_alc),
                   ingred_sour = if_else(str_detect(ingredient, "bitter"), 0, ingred_sour),
                   ingred_sweet = if_else(str_detect(ingredient, "bitter"), 0, ingred_sweet)) %>%
            group_by(row_id) %>%
            mutate(drink_shaken = if_else((sum(ingred_alc, na.rm = TRUE) + sum(spirit, na.rm = TRUE) + sum(ingred_bitter, na.rm = TRUE) >= 0.66*n()) 
                                          & sum(str_detect(ingredient, fruit_sour), na.rm = TRUE) == 0, 0, 1)) %>%
            ungroup()
```


## Measure cleaning

```{r}
boston <- boston %>%
            mutate(measure = if_else(str_detect(measure, "oz"), str_replace(measure, regex("(?=oz)"), ""), measure),
                   measure = if_else(str_detect(measure, "ml"), str_replace(measure, regex("(?=ml)"), ""), measure)) %>%
            filter(str_detect(measure, "oz") | str_detect(measure, "ml") | str_detect(measure, "tsp") | str_detect(measure, "splash") | str_detect(measure, "dashes")) %>%
            filter(str_detect(measure, "750-ml") == FALSE)

boston <- boston %>%
            mutate(unit = case_when(str_detect(measure, "oz") ~ "oz",
                                       str_detect(measure, "ml") ~ "ml",
                                       str_detect(measure, "tsp") ~ "tsp",
                                       str_detect(measure, "splash") ~ "splash",
                                       str_detect(measure, "dashes") ~ "dashes",
                                       TRUE ~ NA_character_))

boston <- boston %>%
            mutate(measure = case_when(str_detect(measure, "2 1/2") ~ "2.5",
                                       str_detect(measure, "2 1/4") ~ "2.25",
                                       str_detect(measure, "1 2/3") ~ "1.66",
                                       str_detect(measure, "1 1/4") ~ "1.25",
                                       str_detect(measure, "1/4") ~ "0.25",
                                       str_detect(measure, "1/3") ~ "0.33",
                                       str_detect(measure, "1 1/2") ~ "1.5",
                                       str_detect(measure, "1/2") ~ "0.5",
                                       str_detect(measure, "1 3/4") ~ "1.75",
                                       str_detect(measure, "3/4") ~ "0.75",
                                       TRUE ~ measure),
                   measure = case_when(unit == "oz" ~ as.numeric(str_trim(str_replace(measure, "oz", ""), side = "both")),
                                       unit == "ml" ~ as.numeric(str_trim(str_replace(measure, "ml", ""), side = "both"))*0.033814,
                                       unit == "tsp" ~ as.numeric(str_trim(str_replace(measure, "tsp", ""), side = "both"))*0.166667,
                                       unit == "splash" ~ 0.2,
                                       unit == "dashes" ~ as.numeric(str_trim(str_replace(measure, "dashes", ""), side = "both"))*0.03125,
                                       TRUE ~ NA_real_))
```


## Ratios

```{r}
## Realized that I messed up and that it was actually better to have the descriptors as text, not as booleans
boston <- boston %>%
            select(-unit) %>%
            pivot_longer(-c(name, category, row_id, ingredient_number, ingredient, measure, drink_shaken), names_to = "type", values_to = "value") %>%
            group_by(name, ingredient_number) %>%
            slice(which.max(value)) %>%
            ungroup() %>%
            mutate(type = str_replace_all(type, "ingred_", ""),
                   type = str_replace_all(type, "alc", "alcoholic")) %>%
            select(-value) %>%
            arrange(row_id)
```

```{r}
drinks <- boston %>%
            group_by(name, type) %>%
            summarize(total_oz = sum(measure, na.rm = TRUE),
                      drink_shaken = max(drink_shaken, na.rm = TRUE)) %>%
            pivot_wider(names_from = type, values_from = total_oz) %>%
            group_by(name) %>%
            summarize(drink_shaken = max(drink_shaken, na.rm = TRUE),
                      parts_spirit = 1,
                      parts_alcoholic = alcoholic / spirit,
                      parts_sweet = sweet / spirit,
                      parts_sour = sour / spirit,
                      parts_bitter = bitter / spirit)
```

```{r}
dark_orange <- "#d25d3c"
light_orange <- "#fa8775"
pink <- "#ea5f94"
tan <- "#eecc99"
light_grey <- "#cdcfd6"
light_purple <- "#95a1bd"
blue <- "#4477bb"
```


```{r}
CairoPNG(filename = "week-22-cocktail-parts-ratios.png", width = 16, height = 9, units = "in", dpi = 300)

drinks %>%
  pivot_longer(-c(name, drink_shaken), names_to = "type", values_to = "parts") %>%
  filter(name != "Applejack Punch") %>%
  mutate(type = str_to_title(str_replace_all(type, "parts_", "")),
         shaken = if_else(drink_shaken == 0, "Stirred", "Shaken")) %>%
  filter(type != "Spirit") %>%
  ggplot(aes(x = parts, y = type, fill = type)) +
    geom_density_ridges2(aes(point_colour = type),
                         quantile_lines = TRUE, quantiles = c(0.25, 0.5, 0.75),
                         jittered_points = TRUE, position = "raincloud", point_alpha = 0.3, scale = 1.0) +
    scale_fill_manual(values = c(light_grey, dark_orange, pink, tan)) +
    scale_discrete_manual("point_colour", values = c(light_grey, dark_orange, pink, tan)) +
    scale_x_continuous(breaks = seq(0, 6, 1)) +
    facet_wrap(~shaken, ncol = 1) +
    guides(fill = FALSE,
           point_colour = FALSE) +
    theme_light() +
    labs(title = "How do stirred and shaken drinks differ in their parts ratios of sweet, sour, and bitter ingredients?",
         subtitle = "Shaken drinks appear to have more extreme values in sweet/sour ingredients, whereas Stirred drinks have more extreme values in bitter/alcoholic ingredients;\nParts ratios calculated relative to the total ounces of hard liquor/spirit of the drink",
         x = "Parts",
         y = NULL) +
    theme(plot.background = element_rect(fill = "#fffbf0"),
          panel.background = element_rect(fill = "#fffbf0"),
          strip.background = element_blank(),
          text = element_text(family = "CMU Serif"),
          strip.text = element_text(colour = "black", size = 12),
          title = element_text(size = 14),
          plot.subtitle = element_text(size = 14),
          axis.title = element_text(size = 12),
          axis.text = element_text(size = 12))

dev.off()
```



























