---
title: "Tidy Tuesday Week 11 - FIFA 2010 World Cup Audiences"
author: "Hayden MacDonald"
date: "2018/06/12"
output:
  html_document: default
  pdf_document: default
---

```{r setup, echo=FALSE}
library(formatR)
library(knitr)
opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=50),tidy=TRUE)

library(readxl)
library(dplyr)
library(ggplot2)
library(ggrepel)
```

```{r}
library(fivethirtyeight)
fifa <- fivethirtyeight::fifa_audience
glimpse(fifa)
```

```{r}
palette <- c("#d73027","#f46d43","#fdae61","#fee090","#abd9e9","#4575b4")

fifaplot <- fifa %>%
    filter(!is.na(tv_audience_share)) %>%
    ggplot() + geom_point(aes(x = population_share, y = tv_audience_share, size = gdp_weighted_share, color = confederation)) + scale_x_log10() + labs(title = "FIFA World Cup 2010 Viewership", subtitle = "Percent share of global TV audience over log percent share of global population", x = "Log Percent Share of Global Population", y = "Percent TV Audience Share") + scale_colour_manual(name = "Confederation", values = palette) + scale_size_continuous(name = "GDP Weighted TV Audience Share (%)") + theme(plot.subtitle = element_text(vjust = 1), 
    plot.caption = element_text(vjust = 1), 
    axis.line = element_line(size = 0.5, 
        linetype = "solid"), axis.ticks = element_line(colour = "black"), 
    panel.grid.major = element_line(colour = "gray92"), 
    panel.grid.minor = element_line(linetype = "blank"), 
    panel.background = element_rect(fill = NA), 
    legend.key = element_rect(fill = "white"), 
    legend.background = element_rect(fill = "white"),
    legend.position = c(0.25, 0.65))
```
\pagebreak
```{r}
#Who are the countries with the highest GDP Weighted TV Audience Share?
top9 <- fifa %>%
    filter(!is.na(tv_audience_share)) %>%
    arrange(desc(gdp_weighted_share)) %>%
    top_n(9)

top9

#"United Kingdom" is too long to be a tidy labelpwd

top9[6, 1] <- "UK"

fifaplot2 <- fifaplot + geom_text_repel(data = top9, aes(x = population_share, y = tv_audience_share, label = country), box.padding = 1.5, point.padding = 0.6)
```

```{r}
ggsave("FIFA World Cup 2010 Viewership.png", plot = fifaplot2, device = "png", dpi = 300, path = "C:/Users/Hayden/Documents/hmd-tidy-tuesday/week11")
```




